### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by ezevin** [learn-co-curriculum/fewpjs-js-fundamentals-collections#3]
ASIDE: "Garfield" might actually pretty cool. Many comics fans have suspected Jim Davis, Garfield's creator, might be doing some sort of existentialist pop art, prefiguring "The Good Place by ~ 40 years.

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

Since the reference was confusing, we have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
